name: bmi_calculator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter  
  iconsax: ^0.0.8
  intl: ^0.18.1
  path: ^1.8.3
  provider: ^6.1.1
  rive: ^0.12.4
  sqflite: ^2.3.0
  syncfusion_flutter_sliders: ^24.2.7

dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/character_boy.png
    - assets/images/character_girl.png
    - assets/images/box_empty.png

    - assets/animations/character_boy.riv
    - assets/animations/character_girl.riv
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

  
